# Generated by Django 3.2.8 on 2021-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
